# fly.toml app configuration file generated for lapa-casa-hostel on 2026-09-02T13:35:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lapa-casa-hostel'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'production'

[env]
  API_VERSION = 'v1'
  EMAIL_FROM = 'lapalandiarj@gmail.com'
  EMAIL_FROM_NAME = 'Lapa Casa'
  FROM_EMAIL = 'lapalandiarj@gmail.com'
  FRONTEND_URL = 'https://lapacasario.com'
  GOOGLE_SHEETS_SHEET_NAME = 'Hoja 1'
  JWT_EXPIRES_IN = '7d'
  NODE_ENV = 'production'
  PORT = '5000'
  TIMEZONE = 'America/Sao_Paulo'

[processes]
  app = 'npm run start'
  worker = 'npm run worker'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  processes = ['worker']
