// frontend/src/components/booking/hostel-engine.types.ts
// Tipos TypeScript · Traducciones PT/ES/EN · DEFAULT_ROOMS · DAY_LBL · MON_LBL

// ─── Tipos base ─────────────────────────────────────────
export type Lang = 'pt' | 'es' | 'en' | 'fr' | 'de' | 'it';
export type Phase = 'wizard' | 'success' | 'expired';
export type PayMethod = 'pix' | 'card';

export interface RoomDef {
  id: string;
  realId?: string;
  name: string;
  type: 'mixed' | 'female';
  capacity: number;
  available: number;
  price: number;
  isFlexible: boolean;
}

export interface FormState {
  name: string;
  email: string;
  email2: string;
  phone: string;
  country: string;
  doc: string;
  arrival: string;
  requests: string;
}

export interface FormErrors {
  name?: string;
  email?: string;
  email2?: string;
  phone?: string;
  country?: string;
  doc?: string;
  arrival?: string;
}

// ─── Traducciones ────────────────────────────────────────
export const T = {
  pt: {
    step1:'Datas',step2:'Quartos',step3:'Hóspede',step4:'Resumo',
    p1title:'Escolha suas datas',p1sub:'Selecione entrada e saída',
    checkin:'Check-in',checkout:'Check-out',
    calPrev:'Mês anterior',calNext:'Próximo mês',
    seasonMedia:'⛅ Média: ×1.0',seasonAlta:'☀️ Alta (Dez–Mar, Jul–Ago): ×1.5',
    seasonCarnaval:'🎉 Carnaval (mín. 5 noites): ×2.0',seasonBaixa:'🌧 Baixa (Jun, Set): ×0.8',
    p2title:'Selecione os quartos',p2sub:'Quantas camas você precisa?',
    p3title:'Dados do hóspede',p3sub:'Responsável pela reserva',
    lblName:'Nome completo',errName:'Nome completo é obrigatório',
    lblEmail:'E-mail',errEmail:'E-mail inválido',
    lblEmail2:'Confirmar e-mail',errEmail2:'E-mails não coincidem',noPaste:'(não colar)',
    lblPhone:'WhatsApp',errPhone:'Telefone obrigatório',
    lblCountry:'País',errCountry:'País obrigatório',
    selectPlaceholder:'Selecione',optOther:'Outro',
    lblCPF:'CPF',lblPassport:'Passaporte / Documento',
    errCPF:'CPF inválido',errDocForeign:'Documento inválido (mín. 5 caracteres)',
    phCPF:'000.000.000-00',phPassport:'Número do passaporte',
    fbCPFok:'✓ CPF válido',fbCPFerr:'✗ CPF inválido',fbDocOk:'✓ Documento aceito',
    lblArrival:'Horário de chegada',errArrival:'Horário de chegada obrigatório',
    arrivalPlaceholder:'Selecione (14h–22h)',
    lblRequests:'Solicitações especiais',optional:'(opcional)',
    rulesTitle:'Regras da casa',
    rule1:'Check-in: 14h–22h.',
    rule2:'Check-out: até as 12h.',
    rule3:'Documento de identidade obrigatório no check-in.',
    rule4:'Hospedagem permitida a partir de 18 anos.',
    rule5:'Proibido fumar dentro do hostel.',
    cancelBtn:'Política de cancelamento',
    cancelFree:'Grátis',cancelFreeText:'Cancele até 48 horas antes do check-in — reembolso integral do depósito.',
    cancelNo:'Não reembolsável',cancelNoText:'Cancelamento nas últimas 48 horas ou no-show — depósito retido.',
    p4title:'Resumo da reserva',p4sub:'Revise antes de confirmar',
    sumDatesHead:'Datas e Quartos',sumPriceHead:'Preço',sumGuestHead:'Hóspede',
    pmPix:'PIX',pmPixApproval:'Aprovação imediata',pmCard:'Cartão de crédito',
    btnConfirm:'Confirmar reserva',btnWhatsApp:'Confirmar por WhatsApp',
    successTitle:'Reserva confirmada!',successSub:'Enviamos os detalhes por e-mail e WhatsApp',
    pixDepLabel:'Depósito PIX',cardDepLabel:'Pagamento com cartão',
    cardInstruction:'Você receberá o link de pagamento por e-mail.',
    timerLabel:'Expira em',pixKey:'Chave PIX: lapalandiarj@gmail.com',
    restNote:'O restante (70%) é pago no check-in, em dinheiro ou cartão.',
    btnNewBooking:'Nova reserva',
    expiredTitle:'Reserva não concluída',expiredSub:'O tempo expirou. As vagas foram liberadas.',
    btnTryAgain:'Tentar novamente',
    priceBase:'Base por noite',btnBack:'Voltar',btnNext:'Próximo',
    discountActive:'Desconto de grupo ativo!',
    flexibleNotice:'Cuarto 6 — Solo Mujeres: quarto feminino por padrão. Converte para misto 48h antes do check-in se necessário.',
    tNights:'Noites',tTotalBeds:'Total de camas',tGroupDisc:'Desconto de grupo',
    tTotal:'Total',tDepositNow:'Depósito agora (PIX/Cartão)',tAtCheckin:'no check-in',
    tNight:'noite',tNights2:'noites',tBed:'cama',tBeds:'camas',
    tSelectCheckout:'Selecione check-out',tClickCheckout:'Clique em uma data de saída',
    tInProgress:'em curso',tCountryLabel:'País',
    tToastCheckin:'Selecione a data de check-in.',tToastCheckout:'Selecione a data de check-out.',
    tToastMinNights:'estadia mínima de',tToastNights:'noites.',
    tToastBeds:'Selecione pelo menos 1 cama.',
    otaDirect:'Reservar direto economiza',otaVs:'em relação ao Airbnb/Booking',
    directBanner:'Preço direto garantido · Sem comissões · Confirmação imediata',
    errorBooking:'Erro ao criar reserva. Tente novamente.',
    waGreet:'Olá! Quero reservar no Lapa Casa Hostel.',
    waAwait:'Aguardo confirmação. Obrigado!',
    cardGoToPayment:'Ir para o pagamento com cartão →',
    pmPixRec:'Recomendado',
    pmPixOffer:'Sem comissão · Preço direto',
    pmCardFee:'10% acréscimo com cartão',
    pmCardNote:'Nacional ou internacional',
    pmCardTotal:'Total com cartão',
    pmNote:'PIX: sem acréscimo. Cartão: 10% adicional.',
    pmPixUnavailable:'Disponível apenas no Brasil',
  },
  es: {
    step1:'Fechas',step2:'Cuartos',step3:'Huésped',step4:'Resumen',
    p1title:'Elige tus fechas',p1sub:'Selecciona entrada y salida',
    checkin:'Check-in',checkout:'Check-out',
    calPrev:'Mes anterior',calNext:'Mes siguiente',
    seasonMedia:'⛅ Media: ×1.0',seasonAlta:'☀️ Alta (Dic–Mar, Jul–Ago): ×1.5',
    seasonCarnaval:'🎉 Carnaval (mín. 5 noches): ×2.0',seasonBaixa:'🌧 Baja (Jun, Sep): ×0.8',
    p2title:'Selecciona los cuartos',p2sub:'¿Cuántas camas necesitas?',
    p3title:'Datos del huésped',p3sub:'Responsable de la reserva',
    lblName:'Nombre completo',errName:'Nombre completo es obligatorio',
    lblEmail:'Correo electrónico',errEmail:'Correo inválido',
    lblEmail2:'Confirmar correo',errEmail2:'Los correos no coinciden',noPaste:'(no pegar)',
    lblPhone:'WhatsApp',errPhone:'Teléfono obligatorio',
    lblCountry:'País',errCountry:'País obligatorio',
    selectPlaceholder:'Seleccionar',optOther:'Otro',
    lblCPF:'CPF',lblPassport:'Pasaporte / Documento',
    errCPF:'CPF inválido',errDocForeign:'Documento inválido (mín. 5 caracteres)',
    phCPF:'000.000.000-00',phPassport:'Número de pasaporte',
    fbCPFok:'✓ CPF válido',fbCPFerr:'✗ CPF inválido',fbDocOk:'✓ Documento aceptado',
    lblArrival:'Hora de llegada',errArrival:'Hora de llegada obligatoria',
    arrivalPlaceholder:'Seleccionar (14h–22h)',
    lblRequests:'Solicitudes especiales',optional:'(opcional)',
    rulesTitle:'Normas de la casa',
    rule1:'Check-in: 14h–22h.',
    rule2:'Check-out: hasta las 12h.',
    rule3:'Documento de identidad obligatorio en el check-in.',
    rule4:'Hospedaje permitido a partir de 18 años.',
    rule5:'Prohibido fumar dentro del hostel.',
    cancelBtn:'Política de cancelación',
    cancelFree:'Gratis',cancelFreeText:'Cancela hasta 48 horas antes del check-in — reembolso total del depósito.',
    cancelNo:'No reembolsable',cancelNoText:'Cancelación en las últimas 48 horas o no-show — depósito retenido.',
    p4title:'Resumen de la reserva',p4sub:'Revisa antes de confirmar',
    sumDatesHead:'Fechas y Cuartos',sumPriceHead:'Precio',sumGuestHead:'Huésped',
    pmPix:'PIX',pmPixApproval:'Aprobación inmediata',pmCard:'Tarjeta de crédito',
    btnConfirm:'Confirmar reserva',btnWhatsApp:'Confirmar por WhatsApp',
    successTitle:'¡Reserva confirmada!',successSub:'Te enviamos los detalles por e-mail y WhatsApp',
    pixDepLabel:'Depósito PIX',cardDepLabel:'Pago con tarjeta',
    cardInstruction:'Recibirás el enlace de pago por e-mail.',
    timerLabel:'Expira en',pixKey:'Clave PIX: lapalandiarj@gmail.com',
    restNote:'El resto (70%) se paga en el check-in, en efectivo o tarjeta.',
    btnNewBooking:'Nueva reserva',
    expiredTitle:'Reserva no concretada',expiredSub:'El tiempo expiró. Los espacios fueron liberados.',
    btnTryAgain:'Intentar de nuevo',
    priceBase:'Base por noche',btnBack:'Volver',btnNext:'Siguiente',
    discountActive:'¡Descuento de grupo activo!',
    flexibleNotice:'Cuarto 6 — Solo Mujeres: habitación femenina por defecto. Se convierte a mixto 48h antes del check-in si es necesario.',
    tNights:'Noches',tTotalBeds:'Total de camas',tGroupDisc:'Descuento de grupo',
    tTotal:'Total',tDepositNow:'Depósito ahora (PIX/Tarjeta)',tAtCheckin:'en el check-in',
    tNight:'noche',tNights2:'noches',tBed:'cama',tBeds:'camas',
    tSelectCheckout:'Seleccionar check-out',tClickCheckout:'Haz clic en una fecha de salida',
    tInProgress:'en curso',tCountryLabel:'País',
    tToastCheckin:'Selecciona la fecha de check-in.',tToastCheckout:'Selecciona la fecha de check-out.',
    tToastMinNights:'estancia mínima de',tToastNights:'noches.',
    tToastBeds:'Selecciona al menos 1 cama.',
    otaDirect:'Reservar directo ahorra',otaVs:'vs Airbnb/Booking',
    directBanner:'Precio directo garantizado · Sin comisiones · Confirmación inmediata',
    errorBooking:'Error al crear la reserva. Inténtalo de nuevo.',
    waGreet:'¡Hola! Quiero reservar en Lapa Casa Hostel.',
    waAwait:'Quedo a la espera de confirmación. ¡Gracias!',
    cardGoToPayment:'Ir al pago con tarjeta →',
    pmPixRec:'Recomendado',
    pmPixOffer:'Sin comisión · Precio directo',
    pmCardFee:'10% adicional con tarjeta',
    pmCardNote:'Nacional o internacional',
    pmCardTotal:'Total con tarjeta',
    pmNote:'PIX: sin cargo. Tarjeta: 10% adicional.',
    pmPixUnavailable:'Disponible solo en Brasil',
  },
  en: {
    step1:'Dates',step2:'Rooms',step3:'Guest',step4:'Summary',
    p1title:'Choose your dates',p1sub:'Select check-in and check-out',
    checkin:'Check-in',checkout:'Check-out',
    calPrev:'Previous month',calNext:'Next month',
    seasonMedia:'⛅ Mid season: ×1.0',seasonAlta:'☀️ High (Dec–Mar, Jul–Aug): ×1.5',
    seasonCarnaval:'🎉 Carnival (min. 5 nights): ×2.0',seasonBaixa:'🌧 Low (Jun, Sep): ×0.8',
    p2title:'Select your rooms',p2sub:'How many beds do you need?',
    p3title:'Guest details',p3sub:'Booking contact',
    lblName:'Full name',errName:'Full name is required',
    lblEmail:'Email',errEmail:'Invalid email',
    lblEmail2:'Confirm email',errEmail2:'Emails do not match',noPaste:'(no paste)',
    lblPhone:'WhatsApp',errPhone:'Phone number required',
    lblCountry:'Country',errCountry:'Country required',
    selectPlaceholder:'Select',optOther:'Other',
    lblCPF:'CPF',lblPassport:'Passport / ID',
    errCPF:'Invalid CPF',errDocForeign:'Invalid document (min. 5 characters)',
    phCPF:'000.000.000-00',phPassport:'Passport number',
    fbCPFok:'✓ Valid CPF',fbCPFerr:'✗ Invalid CPF',fbDocOk:'✓ Document accepted',
    lblArrival:'Arrival time',errArrival:'Arrival time required',
    arrivalPlaceholder:'Select (2 pm–10 pm)',
    lblRequests:'Special requests',optional:'(optional)',
    rulesTitle:'House rules',
    rule1:'Check-in: 2 pm–10 pm.',
    rule2:'Check-out: by 12 pm.',
    rule3:'ID required at check-in.',
    rule4:'Guests must be 18 or older.',
    rule5:'Smoking inside the hostel is not allowed.',
    cancelBtn:'Cancellation policy',
    cancelFree:'Free',cancelFreeText:'Cancel up to 48 hours before check-in — full deposit refund.',
    cancelNo:'Non-refundable',cancelNoText:'Cancellation within 48 hours or no-show — deposit forfeited.',
    p4title:'Booking summary',p4sub:'Review before confirming',
    sumDatesHead:'Dates & Rooms',sumPriceHead:'Price',sumGuestHead:'Guest',
    pmPix:'PIX',pmPixApproval:'Instant approval',pmCard:'Credit card',
    btnConfirm:'Confirm booking',btnWhatsApp:'Confirm via WhatsApp',
    successTitle:'Booking confirmed!',successSub:'We sent the details to your email and WhatsApp',
    pixDepLabel:'PIX deposit',cardDepLabel:'Card payment',
    cardInstruction:'You will receive the payment link by email.',
    timerLabel:'Expires in',pixKey:'PIX key: lapalandiarj@gmail.com',
    restNote:'The remaining 70% is due at check-in, in cash or by card.',
    btnNewBooking:'New booking',
    expiredTitle:'Booking not completed',expiredSub:'Time expired. The beds have been released.',
    btnTryAgain:'Try again',
    priceBase:'Base per night',btnBack:'Back',btnNext:'Next',
    discountActive:'Group discount active!',
    flexibleNotice:'Room 6 — Women Only: female dorm by default. Converts to mixed 48h before check-in if needed.',
    tNights:'Nights',tTotalBeds:'Total beds',tGroupDisc:'Group discount',
    tTotal:'Total',tDepositNow:'Deposit now (PIX/Card)',tAtCheckin:'at check-in',
    tNight:'night',tNights2:'nights',tBed:'bed',tBeds:'beds',
    tSelectCheckout:'Select check-out',tClickCheckout:'Click a check-out date',
    tInProgress:'in progress',tCountryLabel:'Country',
    tToastCheckin:'Select a check-in date.',tToastCheckout:'Select a check-out date.',
    tToastMinNights:'minimum stay of',tToastNights:'nights.',
    tToastBeds:'Select at least 1 bed.',
    otaDirect:'Booking direct saves you',otaVs:'vs Airbnb/Booking',
    directBanner:'Best rate guaranteed · No platform fees · Instant confirmation',
    errorBooking:'Error creating booking. Please try again.',
    waGreet:'Hello! I would like to book at Lapa Casa Hostel.',
    waAwait:'Looking forward to your confirmation. Thank you!',
    cardGoToPayment:'Go to card payment →',
    pmPixRec:'Recommended',
    pmPixOffer:'No fees · Direct price',
    pmCardFee:'10% added for card',
    pmCardNote:'Domestic or international',
    pmCardTotal:'Total with card',
    pmNote:'PIX: no surcharge. Card: 10% added.',
    pmPixUnavailable:'Available in Brazil only',
  },
  fr: {
    step1:'Dates',step2:'Chambres',step3:'Voyageur',step4:'Récapitulatif',
    p1title:'Choisissez vos dates',p1sub:'Sélectionnez arrivée et départ',
    checkin:'Arrivée',checkout:'Départ',
    calPrev:'Mois précédent',calNext:'Mois suivant',
    seasonMedia:'⛅ Moyenne: ×1.0',seasonAlta:'☀️ Haute (Déc–Mar, Juil–Août): ×1.5',
    seasonCarnaval:'🎉 Carnaval (min. 5 nuits): ×2.0',seasonBaixa:'🌧 Basse (Juin, Sep): ×0.8',
    p2title:'Sélectionnez les chambres',p2sub:'De combien de lits avez-vous besoin?',
    p3title:'Informations du voyageur',p3sub:'Responsable de la réservation',
    lblName:'Nom complet',errName:'Le nom complet est obligatoire',
    lblEmail:'E-mail',errEmail:'E-mail invalide',
    lblEmail2:'Confirmer l\'e-mail',errEmail2:'Les e-mails ne correspondent pas',noPaste:'(ne pas coller)',
    lblPhone:'WhatsApp',errPhone:'Téléphone obligatoire',
    lblCountry:'Pays',errCountry:'Pays obligatoire',
    selectPlaceholder:'Sélectionner',optOther:'Autre',
    lblCPF:'CPF',lblPassport:'Passeport / Pièce d\'identité',
    errCPF:'CPF invalide',errDocForeign:'Document invalide (min. 5 caractères)',
    phCPF:'000.000.000-00',phPassport:'Numéro de passeport',
    fbCPFok:'✓ CPF valide',fbCPFerr:'✗ CPF invalide',fbDocOk:'✓ Document accepté',
    lblArrival:'Heure d\'arrivée',errArrival:'Heure d\'arrivée obligatoire',
    arrivalPlaceholder:'Sélectionner (14h–22h)',
    lblRequests:'Demandes spéciales',optional:'(facultatif)',
    rulesTitle:'Règlement intérieur',
    rule1:'Check-in: 14h–22h.',
    rule2:'Check-out: avant 12h.',
    rule3:'Pièce d\'identité obligatoire au check-in.',
    rule4:'Hébergement réservé aux plus de 18 ans.',
    rule5:'Interdiction de fumer dans l\'hostel.',
    cancelBtn:'Politique d\'annulation',
    cancelFree:'Gratuit',cancelFreeText:'Annulez jusqu\'à 48h avant le check-in — remboursement intégral du dépôt.',
    cancelNo:'Non remboursable',cancelNoText:'Annulation dans les 48h ou no-show — dépôt conservé.',
    p4title:'Récapitulatif de la réservation',p4sub:'Vérifiez avant de confirmer',
    sumDatesHead:'Dates et Chambres',sumPriceHead:'Prix',sumGuestHead:'Voyageur',
    pmPix:'PIX',pmPixApproval:'Approbation immédiate',pmCard:'Carte de crédit',
    btnConfirm:'Confirmer la réservation',btnWhatsApp:'Confirmer par WhatsApp',
    successTitle:'Réservation confirmée!',successSub:'Nous vous avons envoyé les détails par e-mail et WhatsApp',
    pixDepLabel:'Acompte PIX',cardDepLabel:'Paiement par carte',
    cardInstruction:'Vous recevrez le lien de paiement par e-mail.',
    timerLabel:'Expire dans',pixKey:'Clé PIX: lapalandiarj@gmail.com',
    restNote:'Les 70% restants sont payables au check-in, en espèces ou par carte.',
    btnNewBooking:'Nouvelle réservation',
    expiredTitle:'Réservation non finalisée',expiredSub:'Le délai est expiré. Les lits ont été libérés.',
    btnTryAgain:'Réessayer',
    priceBase:'Base par nuit',btnBack:'Retour',btnNext:'Suivant',
    discountActive:'Réduction de groupe active!',
    flexibleNotice:'Chambre 6 — Femmes uniquement: dortoir féminin par défaut. Converti en mixte 48h avant le check-in si nécessaire.',
    tNights:'Nuits',tTotalBeds:'Total des lits',tGroupDisc:'Réduction de groupe',
    tTotal:'Total',tDepositNow:'Acompte (PIX/Carte)',tAtCheckin:'au check-in',
    tNight:'nuit',tNights2:'nuits',tBed:'lit',tBeds:'lits',
    tSelectCheckout:'Sélectionner le départ',tClickCheckout:'Cliquez sur une date de départ',
    tInProgress:'en cours',tCountryLabel:'Pays',
    tToastCheckin:'Sélectionnez la date d\'arrivée.',tToastCheckout:'Sélectionnez la date de départ.',
    tToastMinNights:'séjour minimum de',tToastNights:'nuits.',
    tToastBeds:'Sélectionnez au moins 1 lit.',
    otaDirect:'Réserver en direct économise',otaVs:'vs Airbnb/Booking',
    directBanner:'Meilleur tarif garanti · Sans commission · Confirmation immédiate',
    errorBooking:'Erreur lors de la réservation. Veuillez réessayer.',
    waGreet:'Bonjour ! Je souhaite réserver au Lapa Casa Hostel.',
    waAwait:'Dans l\'attente de votre confirmation. Merci !',
    cardGoToPayment:'Accéder au paiement par carte →',
    pmPixRec:'Recommandé',
    pmPixOffer:'Sans frais · Prix direct',
    pmCardFee:'10% supplément carte',
    pmCardNote:'Nationale ou internationale',
    pmCardTotal:'Total avec carte',
    pmNote:'PIX: sans frais. Carte: +10%.',
    pmPixUnavailable:'Disponible au Brésil uniquement',
  },
  de: {
    step1:'Daten',step2:'Zimmer',step3:'Gast',step4:'Übersicht',
    p1title:'Wählen Sie Ihre Daten',p1sub:'An- und Abreisedatum auswählen',
    checkin:'Anreise',checkout:'Abreise',
    calPrev:'Vorheriger Monat',calNext:'Nächster Monat',
    seasonMedia:'⛅ Zwischensaison: ×1.0',seasonAlta:'☀️ Hochsaison (Dez–Mär, Jul–Aug): ×1.5',
    seasonCarnaval:'🎉 Karneval (mind. 5 Nächte): ×2.0',seasonBaixa:'🌧 Nebensaison (Jun, Sep): ×0.8',
    p2title:'Zimmer auswählen',p2sub:'Wie viele Betten benötigen Sie?',
    p3title:'Gästedaten',p3sub:'Verantwortlich für die Buchung',
    lblName:'Vollständiger Name',errName:'Vollständiger Name ist erforderlich',
    lblEmail:'E-Mail',errEmail:'Ungültige E-Mail',
    lblEmail2:'E-Mail bestätigen',errEmail2:'E-Mail-Adressen stimmen nicht überein',noPaste:'(nicht einfügen)',
    lblPhone:'WhatsApp',errPhone:'Telefonnummer erforderlich',
    lblCountry:'Land',errCountry:'Land erforderlich',
    selectPlaceholder:'Auswählen',optOther:'Andere',
    lblCPF:'CPF',lblPassport:'Reisepass / Ausweis',
    errCPF:'Ungültige CPF',errDocForeign:'Ungültiges Dokument (mind. 5 Zeichen)',
    phCPF:'000.000.000-00',phPassport:'Reisepassnummer',
    fbCPFok:'✓ CPF gültig',fbCPFerr:'✗ CPF ungültig',fbDocOk:'✓ Dokument akzeptiert',
    lblArrival:'Ankunftszeit',errArrival:'Ankunftszeit erforderlich',
    arrivalPlaceholder:'Auswählen (14–22 Uhr)',
    lblRequests:'Sonderwünsche',optional:'(optional)',
    rulesTitle:'Hausregeln',
    rule1:'Check-in: 14–22 Uhr.',
    rule2:'Check-out: bis 12 Uhr.',
    rule3:'Personalausweis beim Check-in erforderlich.',
    rule4:'Unterkunft nur für Personen ab 18 Jahren.',
    rule5:'Rauchen im Hostel ist verboten.',
    cancelBtn:'Stornierungsbedingungen',
    cancelFree:'Kostenlos',cancelFreeText:'Bis 48 Stunden vor dem Check-in stornieren — volle Rückerstattung der Anzahlung.',
    cancelNo:'Nicht erstattungsfähig',cancelNoText:'Stornierung in den letzten 48 Stunden oder No-Show — Anzahlung wird einbehalten.',
    p4title:'Buchungsübersicht',p4sub:'Vor der Bestätigung prüfen',
    sumDatesHead:'Daten & Zimmer',sumPriceHead:'Preis',sumGuestHead:'Gast',
    pmPix:'PIX',pmPixApproval:'Sofortige Genehmigung',pmCard:'Kreditkarte',
    btnConfirm:'Buchung bestätigen',btnWhatsApp:'Per WhatsApp bestätigen',
    successTitle:'Buchung bestätigt!',successSub:'Wir haben die Details per E-Mail und WhatsApp gesendet',
    pixDepLabel:'PIX-Anzahlung',cardDepLabel:'Kartenzahlung',
    cardInstruction:'Sie erhalten den Zahlungslink per E-Mail.',
    timerLabel:'Läuft ab in',pixKey:'PIX-Schlüssel: lapalandiarj@gmail.com',
    restNote:'Die verbleibenden 70% werden beim Check-in bar oder per Karte bezahlt.',
    btnNewBooking:'Neue Buchung',
    expiredTitle:'Buchung nicht abgeschlossen',expiredSub:'Zeit abgelaufen. Die Betten wurden freigegeben.',
    btnTryAgain:'Erneut versuchen',
    priceBase:'Grundpreis pro Nacht',btnBack:'Zurück',btnNext:'Weiter',
    discountActive:'Gruppenrabatt aktiv!',
    flexibleNotice:'Zimmer 6 — Nur Frauen: standardmäßig Frauenschlafraum. Wird 48h vor dem Check-in bei Bedarf gemischt.',
    tNights:'Nächte',tTotalBeds:'Betten gesamt',tGroupDisc:'Gruppenrabatt',
    tTotal:'Gesamt',tDepositNow:'Anzahlung (PIX/Karte)',tAtCheckin:'beim Check-in',
    tNight:'Nacht',tNights2:'Nächte',tBed:'Bett',tBeds:'Betten',
    tSelectCheckout:'Abreise auswählen',tClickCheckout:'Klicken Sie auf ein Abreisedatum',
    tInProgress:'läuft',tCountryLabel:'Land',
    tToastCheckin:'Bitte wählen Sie ein Anreisedatum.',tToastCheckout:'Bitte wählen Sie ein Abreisedatum.',
    tToastMinNights:'Mindestaufenthalt von',tToastNights:'Nächten.',
    tToastBeds:'Bitte wählen Sie mindestens 1 Bett.',
    otaDirect:'Direktbuchung spart',otaVs:'vs Airbnb/Booking',
    directBanner:'Bestpreis garantiert · Keine Provisionen · Sofortbestätigung',
    errorBooking:'Fehler bei der Buchungserstellung. Bitte erneut versuchen.',
    waGreet:'Hallo! Ich möchte im Lapa Casa Hostel buchen.',
    waAwait:'Ich freue mich auf Ihre Bestätigung. Vielen Dank!',
    cardGoToPayment:'Zur Kartenzahlung →',
    pmPixRec:'Empfohlen',
    pmPixOffer:'Keine Gebühren · Direktpreis',
    pmCardFee:'10% Aufpreis Karte',
    pmCardNote:'Inland oder Ausland',
    pmCardTotal:'Gesamt mit Karte',
    pmNote:'PIX: ohne Aufpreis. Karte: +10%.',
    pmPixUnavailable:'Nur in Brasilien verfügbar',
  },
  it: {
    step1:'Date',step2:'Camere',step3:'Ospite',step4:'Riepilogo',
    p1title:'Scegli le tue date',p1sub:'Seleziona arrivo e partenza',
    checkin:'Check-in',checkout:'Check-out',
    calPrev:'Mese precedente',calNext:'Mese successivo',
    seasonMedia:'⛅ Media: ×1.0',seasonAlta:'☀️ Alta (Dic–Mar, Lug–Ago): ×1.5',
    seasonCarnaval:'🎉 Carnevale (min. 5 notti): ×2.0',seasonBaixa:'🌧 Bassa (Giu, Set): ×0.8',
    p2title:'Seleziona le camere',p2sub:'Quanti letti ti servono?',
    p3title:'Dati dell\'ospite',p3sub:'Responsabile della prenotazione',
    lblName:'Nome completo',errName:'Il nome completo è obbligatorio',
    lblEmail:'E-mail',errEmail:'E-mail non valida',
    lblEmail2:'Conferma e-mail',errEmail2:'Le e-mail non corrispondono',noPaste:'(non incollare)',
    lblPhone:'WhatsApp',errPhone:'Telefono obbligatorio',
    lblCountry:'Paese',errCountry:'Paese obbligatorio',
    selectPlaceholder:'Seleziona',optOther:'Altro',
    lblCPF:'CPF',lblPassport:'Passaporto / Documento',
    errCPF:'CPF non valido',errDocForeign:'Documento non valido (min. 5 caratteri)',
    phCPF:'000.000.000-00',phPassport:'Numero di passaporto',
    fbCPFok:'✓ CPF valido',fbCPFerr:'✗ CPF non valido',fbDocOk:'✓ Documento accettato',
    lblArrival:'Orario di arrivo',errArrival:'Orario di arrivo obbligatorio',
    arrivalPlaceholder:'Seleziona (14h–22h)',
    lblRequests:'Richieste speciali',optional:'(facoltativo)',
    rulesTitle:'Regole della casa',
    rule1:'Check-in: 14h–22h.',
    rule2:'Check-out: entro le 12h.',
    rule3:'Documento d\'identità obbligatorio al check-in.',
    rule4:'Soggiorno consentito a partire dai 18 anni.',
    rule5:'Vietato fumare all\'interno dell\'hostel.',
    cancelBtn:'Politica di cancellazione',
    cancelFree:'Gratuito',cancelFreeText:'Cancella fino a 48 ore prima del check-in — rimborso completo dell\'acconto.',
    cancelNo:'Non rimborsabile',cancelNoText:'Cancellazione nelle ultime 48 ore o no-show — acconto trattenuto.',
    p4title:'Riepilogo prenotazione',p4sub:'Controlla prima di confermare',
    sumDatesHead:'Date e Camere',sumPriceHead:'Prezzo',sumGuestHead:'Ospite',
    pmPix:'PIX',pmPixApproval:'Approvazione immediata',pmCard:'Carta di credito',
    btnConfirm:'Conferma prenotazione',btnWhatsApp:'Conferma via WhatsApp',
    successTitle:'Prenotazione confermata!',successSub:'Abbiamo inviato i dettagli via e-mail e WhatsApp',
    pixDepLabel:'Acconto PIX',cardDepLabel:'Pagamento con carta',
    cardInstruction:'Riceverai il link di pagamento via e-mail.',
    timerLabel:'Scade tra',pixKey:'Chiave PIX: lapalandiarj@gmail.com',
    restNote:'Il restante 70% è dovuto al check-in, in contanti o con carta.',
    btnNewBooking:'Nuova prenotazione',
    expiredTitle:'Prenotazione non completata',expiredSub:'Il tempo è scaduto. I posti sono stati liberati.',
    btnTryAgain:'Riprova',
    priceBase:'Base per notte',btnBack:'Indietro',btnNext:'Avanti',
    discountActive:'Sconto di gruppo attivo!',
    flexibleNotice:'Camera 6 — Solo Donne: dormitorio femminile per impostazione predefinita. Diventa misto 48h prima del check-in se necessario.',
    tNights:'Notti',tTotalBeds:'Letti totali',tGroupDisc:'Sconto di gruppo',
    tTotal:'Totale',tDepositNow:'Acconto (PIX/Carta)',tAtCheckin:'al check-in',
    tNight:'notte',tNights2:'notti',tBed:'letto',tBeds:'letti',
    tSelectCheckout:'Seleziona check-out',tClickCheckout:'Clicca su una data di partenza',
    tInProgress:'in corso',tCountryLabel:'Paese',
    tToastCheckin:'Seleziona la data di check-in.',tToastCheckout:'Seleziona la data di check-out.',
    tToastMinNights:'soggiorno minimo di',tToastNights:'notti.',
    tToastBeds:'Seleziona almeno 1 letto.',
    otaDirect:'Prenotare direttamente risparmia',otaVs:'vs Airbnb/Booking',
    directBanner:'Miglior tariffa garantita · Nessuna commissione · Conferma immediata',
    errorBooking:'Errore durante la creazione della prenotazione. Riprova.',
    waGreet:'Ciao! Vorrei prenotare al Lapa Casa Hostel.',
    waAwait:'In attesa della vostra conferma. Grazie!',
    cardGoToPayment:'Vai al pagamento con carta →',
    pmPixRec:'Consigliato',
    pmPixOffer:'Senza commissioni · Prezzo diretto',
    pmCardFee:'10% in più con carta',
    pmCardNote:'Nazionale o internazionale',
    pmCardTotal:'Totale con carta',
    pmNote:'PIX: senza costi. Carta: +10%.',
    pmPixUnavailable:'Disponibile solo in Brasile',
  },
} as const;

export type Translations = typeof T[Lang];

// ─── Cuartos por defecto (fallback si la API no responde) ─
export const DEFAULT_ROOMS: RoomDef[] = [
  { id:'cuarto1', name:'Cuarto 1', type:'mixed',  capacity:12, available:12, price:85, isFlexible:false },
  { id:'cuarto3', name:'Cuarto 3', type:'mixed',  capacity:12, available:12, price:85, isFlexible:false },
  { id:'cuarto4', name:'Cuarto 4', type:'mixed',  capacity:7,  available:7,  price:85, isFlexible:false },
  { id:'cuarto5', name:'Cuarto 5', type:'mixed',  capacity:7,  available:7,  price:85, isFlexible:false },
  { id:'cuarto6', name:'Cuarto 6', type:'female', capacity:7,  available:7,  price:85, isFlexible:true  },
];

// ─── Labels de calendario ─────────────────────────────────
export const DAY_LBL: Record<Lang, string[]> = {
  pt:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
  es:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
  en:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
  fr:['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
  de:['So','Mo','Di','Mi','Do','Fr','Sa'],
  it:['Dom','Lun','Mar','Mer','Gio','Ven','Sab'],
};

export const MON_LBL: Record<Lang, string[]> = {
  pt:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
  es:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
  en:['January','February','March','April','May','June','July','August','September','October','November','December'],
  fr:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  de:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  it:['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
};
