// frontend/src/components/booking/hostel-engine.types.ts
// Tipos TypeScript · Traducciones PT/ES/EN · DEFAULT_ROOMS · DAY_LBL · MON_LBL

// ─── Tipos base ─────────────────────────────────────────
export type Lang = 'pt' | 'es' | 'en' | 'fr' | 'de' | 'it';
export type Phase = 'wizard' | 'success' | 'expired' | 'group';
export type PayMethod = 'pix' | 'card';

export interface RoomDef {
  id: string;
  realId?: string;
  /** code real de room_types (backend/database/seeds/0001_seed.sql) -- clave estable para matchear con la API de disponibilidad, a diferencia del name que es solo texto para mostrar. */
  code: string;
  name: string;
  type: 'mixed' | 'female';
  capacity: number;
  available: number;
  price: number;
  isFlexible: boolean;
}

export interface FormState {
  name: string;
  email: string;
  email2: string;
  phone: string;
  country: string;
  doc: string;
  arrival: string;
  requests: string;
  /** Foto del documento (DNI/pasaporte) como data URL base64 — obligatoria */
  docPhotoBase64: string;
  /** Confirmación de que ningún huésped supera los 50 años ni tiene movilidad reducida */
  restrictionAccepted: boolean;
}

export interface FormErrors {
  name?: string;
  email?: string;
  email2?: string;
  phone?: string;
  country?: string;
  doc?: string;
  arrival?: string;
  docPhoto?: string;
  restriction?: string;
}

/** Feedback de validación inline (email/teléfono/documento) — el ícono lo pone la UI, esto solo dice el texto y si está OK. */
export interface FieldFeedback {
  text: string;
  ok: boolean;
}

// ─── Traducciones ────────────────────────────────────────
export const T = {
  pt: {
    step1: 'Datas',
    step2: 'Quartos',
    step3: 'Hóspede',
    step4: 'Resumo',
    p1title: 'Escolha suas datas',
    p1sub: 'Selecione entrada e saída',
    checkin: 'Check-in',
    checkout: 'Check-out',
    calPrev: 'Mês anterior',
    calNext: 'Próximo mês',
    seasonMedia: '⛅ Média: ×1.0',
    seasonAlta: '☀️ Alta (Dez–Mar, Jul–Ago): ×1.5',
    seasonCarnaval: '🎉 Carnaval (mín. 5 noites): ×2.0',
    seasonBaixa: '🌧 Baixa (Jun, Set): ×0.8',
    p2title: 'Selecione os quartos',
    p2sub: 'Quantas camas você precisa?',
    p3title: 'Dados do hóspede',
    p3sub: 'Responsável pela reserva',
    lblName: 'Nome completo',
    errName: 'Nome completo é obrigatório',
    lblEmail: 'E-mail',
    errEmail: 'E-mail inválido',
    lblEmail2: 'Confirmar e-mail',
    errEmail2: 'E-mails não coincidem',
    noPaste: '(não colar)',
    lblPhone: 'WhatsApp',
    errPhone: 'Telefone obrigatório',
    lblCountry: 'País',
    errCountry: 'País obrigatório',
    selectPlaceholder: 'Selecione',
    optOther: 'Outro',
    lblCPF: 'CPF',
    lblPassport: 'Passaporte / Documento',
    errCPF: 'CPF inválido',
    errDocForeign: 'Documento inválido (mín. 5 caracteres)',
    phCPF: '000.000.000-00',
    phPassport: 'Número do passaporte',
    fbCPFok: 'CPF válido',
    fbCPFerr: 'CPF inválido',
    fbDocOk: 'Documento aceito',
    restrictionText: 'Confirmo que li e aceito as regras da casa acima.',
    errRestriction: 'Você deve confirmar que leu e aceita as restrições.',
    lblDocPhoto: 'Foto do documento (RG / Passaporte)',
    docPhotoBtn: 'Toque para tirar foto ou enviar imagem',
    changeDocPhoto: 'Trocar foto',
    errDocPhoto: 'A foto do documento é obrigatória',
    lblArrival: 'Horário de chegada',
    errArrival: 'Horário de chegada obrigatório',
    arrivalPlaceholder: 'Selecione (14h–22h)',
    lblRequests: 'Solicitações especiais',
    optional: '(opcional)',
    rulesTitle: 'Regras da casa',
    rule1: 'Check-in: 14h–22h.',
    rule2: 'Check-out: até as 12h.',
    rule3: 'Documento de identidade obrigatório no check-in.',
    rule4: 'Hospedagem permitida a partir de 18 anos.',
    rule5: 'Proibido fumar dentro do hostel.',
    rule6:
      'Camas beliches de três andares: não indicadas para maiores de 50 anos ou pessoas com mobilidade reduzida.',
    cancelBtn: 'Política de cancelamento',
    cancelNo: 'Não reembolsável',
    cancelNoText:
      'O depósito pago na reserva não é reembolsável em caso de cancelamento ou no-show, independentemente da antecedência.',
    p4title: 'Resumo da reserva',
    p4sub: 'Revise antes de confirmar',
    sumDatesHead: 'Datas e Quartos',
    sumPriceHead: 'Preço',
    sumGuestHead: 'Hóspede',
    pmPix: 'PIX',
    pmPixApproval: 'Aprovação imediata',
    pmCard: 'Cartão de crédito',
    btnConfirm: 'Confirmar reserva',
    btnWhatsApp: 'Confirmar por WhatsApp',
    successTitle: 'Reserva confirmada!',
    successSub: 'Enviamos os detalhes por e-mail e WhatsApp',
    pixDepLabel: 'Depósito PIX',
    cardDepLabel: 'Pagamento com cartão',
    cardInstruction: 'Você receberá o link de pagamento por e-mail.',
    timerLabel: 'Expira em',
    pixKey: 'Chave PIX: lapalandiarj@gmail.com',
    restNote: 'O restante (70%) é pago no check-in, em dinheiro ou cartão.',
    referralTitle: 'Indique um amigo, ganhe um desconto',
    referralBody:
      'Compartilhe este código: seu amigo ganha 10% de desconto e, quando ele reservar, você recebe outro código de 10% para sua próxima estadia.',
    referralCopy: 'Copiar código',
    referralCopied: 'Copiado!',
    btnNewBooking: 'Nova reserva',
    btnBookOwnBed: 'Reservar minha cama →',
    btnChangeMethod: 'Trocar forma de pagamento',
    payInitFailedMsg:
      'Sua reserva está confirmada, mas não conseguimos gerar o código de pagamento agora. Tente novamente ou fale conosco pelo WhatsApp.',
    paymentLinkErrorMsg:
      'Não conseguimos gerar o link de pagamento. Tente novamente ou fale conosco pelo WhatsApp.',
    expiredTitle: 'Reserva não concluída',
    expiredSub: 'O tempo expirou. As vagas foram liberadas.',
    btnTryAgain: 'Tentar novamente',
    priceBase: 'Base por noite',
    btnBack: 'Voltar',
    btnNext: 'Próximo',
    flexibleNotice:
      'Cuarto 6 — Solo Mujeres: quarto feminino por padrão. Converte para misto 48h antes do check-in se necessário.',
    tNights: 'Noites',
    tTotalBeds: 'Total de camas',
    tTotal: 'Total',
    tDepositNow: 'Depósito agora (PIX/Cartão)',
    tAtCheckin: 'no check-in',
    tNight: 'noite',
    tNights2: 'noites',
    tBed: 'cama',
    tBeds: 'camas',
    tSelectCheckout: 'Selecione check-out',
    tClickCheckout: 'Clique em uma data de saída',
    tInProgress: 'em curso',
    tCountryLabel: 'País',
    tToastCheckin: 'Selecione a data de check-in.',
    tToastCheckout: 'Selecione a data de check-out.',
    tToastMinNights: 'estadia mínima de',
    tToastNights: 'noites.',
    tToastBeds: 'Selecione pelo menos 1 cama.',
    otaDirect: 'Reservar direto economiza',
    otaVs: 'em relação ao Airbnb/Booking',
    directBanner: 'Preço direto garantido · Sem comissões · Confirmação imediata',
    errorBooking: 'Erro ao criar reserva. Tente novamente.',
    waGreet: 'Olá! Quero reservar no Lapa Casa Rio.',
    waAwait: 'Aguardo confirmação. Obrigado!',
    cardGoToPayment: 'Ir para o pagamento com cartão →',
    pmPixRec: 'Recomendado',
    pmPixOffer: 'Sem comissão · Preço direto',
    pmCardFee: '10% acréscimo com cartão',
    pmCardNote: 'Nacional ou internacional',
    pmCardTotal: 'Total com cartão',
    pmNote: 'PIX: 30% sem acréscimo · Cartão de crédito: 10% a mais',
    pmPixUnavailable: 'Disponível apenas no Brasil',
    gpOr: 'Ou pagar em grupo',
    gpTitle: 'Um link para todo o grupo',
    gpDesc:
      'Reencaminhe este link por onde quiser. Cada pessoa preenche seus dados e paga sua cama. Quando o último pagar, a reserva é confirmada automaticamente.',
    gpMetaEach: 'cada pessoa paga aprox.',
    gpBtn: 'Gerar link de pagamento em grupo',
    gpLoading: 'Gerando link...',
    gpCopy: 'Copiar link',
    gpCopied: 'Copiado',
    gpShareWa: 'Compartilhar no WhatsApp',
    gpExpire: 'O link expira em 10 minutos.',
    gpErrGeneric: 'Erro ao criar o link. Tente novamente.',
  },
  es: {
    step1: 'Fechas',
    step2: 'Cuartos',
    step3: 'Huésped',
    step4: 'Resumen',
    p1title: 'Elige tus fechas',
    p1sub: 'Selecciona entrada y salida',
    checkin: 'Check-in',
    checkout: 'Check-out',
    calPrev: 'Mes anterior',
    calNext: 'Mes siguiente',
    seasonMedia: '⛅ Media: ×1.0',
    seasonAlta: '☀️ Alta (Dic–Mar, Jul–Ago): ×1.5',
    seasonCarnaval: '🎉 Carnaval (mín. 5 noches): ×2.0',
    seasonBaixa: '🌧 Baja (Jun, Sep): ×0.8',
    p2title: 'Selecciona los cuartos',
    p2sub: '¿Cuántas camas necesitas?',
    p3title: 'Datos del huésped',
    p3sub: 'Responsable de la reserva',
    lblName: 'Nombre completo',
    errName: 'Nombre completo es obligatorio',
    lblEmail: 'Correo electrónico',
    errEmail: 'Correo inválido',
    lblEmail2: 'Confirmar correo',
    errEmail2: 'Los correos no coinciden',
    noPaste: '(no pegar)',
    lblPhone: 'WhatsApp',
    errPhone: 'Teléfono obligatorio',
    lblCountry: 'País',
    errCountry: 'País obligatorio',
    selectPlaceholder: 'Seleccionar',
    optOther: 'Otro',
    lblCPF: 'CPF',
    lblPassport: 'Pasaporte / Documento',
    errCPF: 'CPF inválido',
    errDocForeign: 'Documento inválido (mín. 5 caracteres)',
    phCPF: '000.000.000-00',
    phPassport: 'Número de pasaporte',
    fbCPFok: 'CPF válido',
    fbCPFerr: 'CPF inválido',
    fbDocOk: 'Documento aceptado',
    restrictionText: 'Confirmo que leí y acepto las normas de la casa de arriba.',
    errRestriction: 'Debés confirmar que leíste y aceptás las restricciones.',
    lblDocPhoto: 'Foto del documento (DNI / Pasaporte)',
    docPhotoBtn: 'Tocá para sacar foto o subir imagen',
    changeDocPhoto: 'Cambiar foto',
    errDocPhoto: 'La foto del documento es obligatoria',
    lblArrival: 'Hora de llegada',
    errArrival: 'Hora de llegada obligatoria',
    arrivalPlaceholder: 'Seleccionar (14h–22h)',
    lblRequests: 'Solicitudes especiales',
    optional: '(opcional)',
    rulesTitle: 'Normas de la casa',
    rule1: 'Check-in: 14h–22h.',
    rule2: 'Check-out: hasta las 12h.',
    rule3: 'Documento de identidad obligatorio en el check-in.',
    rule4: 'Hospedaje permitido a partir de 18 años.',
    rule5: 'Prohibido fumar dentro del hostel.',
    rule6:
      'Camas literas de tres pisos: no aptas para mayores de 50 años ni personas con movilidad reducida.',
    cancelBtn: 'Política de cancelación',
    cancelNo: 'No reembolsable',
    cancelNoText:
      'El depósito abonado en la reserva no es reembolsable en caso de cancelación o no-show, sin importar la anticipación.',
    p4title: 'Resumen de la reserva',
    p4sub: 'Revisa antes de confirmar',
    sumDatesHead: 'Fechas y Cuartos',
    sumPriceHead: 'Precio',
    sumGuestHead: 'Huésped',
    pmPix: 'PIX',
    pmPixApproval: 'Aprobación inmediata',
    pmCard: 'Tarjeta de crédito',
    btnConfirm: 'Confirmar reserva',
    btnWhatsApp: 'Confirmar por WhatsApp',
    successTitle: '¡Reserva confirmada!',
    successSub: 'Te enviamos los detalles por e-mail y WhatsApp',
    pixDepLabel: 'Depósito PIX',
    cardDepLabel: 'Pago con tarjeta',
    cardInstruction: 'Recibirás el enlace de pago por e-mail.',
    timerLabel: 'Expira en',
    pixKey: 'Clave PIX: lapalandiarj@gmail.com',
    restNote: 'El resto (70%) se paga en el check-in, en efectivo o tarjeta.',
    referralTitle: 'Recomienda a un amigo, gana un descuento',
    referralBody:
      'Comparte este código: tu amigo tiene 10% de descuento y, cuando reserve, tú recibes otro código de 10% para tu próxima estadía.',
    referralCopy: 'Copiar código',
    referralCopied: '¡Copiado!',
    btnNewBooking: 'Nueva reserva',
    btnBookOwnBed: 'Reservar mi cama →',
    btnChangeMethod: 'Cambiar forma de pago',
    payInitFailedMsg:
      'Tu reserva está confirmada, pero no pudimos generar el código de pago ahora. Probá de nuevo o escribinos por WhatsApp.',
    paymentLinkErrorMsg:
      'No pudimos generar el enlace de pago. Intentá de nuevo o escribinos por WhatsApp.',
    expiredTitle: 'Reserva no concretada',
    expiredSub: 'El tiempo expiró. Los espacios fueron liberados.',
    btnTryAgain: 'Intentar de nuevo',
    priceBase: 'Base por noche',
    btnBack: 'Volver',
    btnNext: 'Siguiente',
    flexibleNotice:
      'Cuarto 6 — Solo Mujeres: habitación femenina por defecto. Se convierte a mixto 48h antes del check-in si es necesario.',
    tNights: 'Noches',
    tTotalBeds: 'Total de camas',
    tTotal: 'Total',
    tDepositNow: 'Depósito ahora (PIX/Tarjeta)',
    tAtCheckin: 'en el check-in',
    tNight: 'noche',
    tNights2: 'noches',
    tBed: 'cama',
    tBeds: 'camas',
    tSelectCheckout: 'Seleccionar check-out',
    tClickCheckout: 'Haz clic en una fecha de salida',
    tInProgress: 'en curso',
    tCountryLabel: 'País',
    tToastCheckin: 'Selecciona la fecha de check-in.',
    tToastCheckout: 'Selecciona la fecha de check-out.',
    tToastMinNights: 'estancia mínima de',
    tToastNights: 'noches.',
    tToastBeds: 'Selecciona al menos 1 cama.',
    otaDirect: 'Reservar directo ahorra',
    otaVs: 'vs Airbnb/Booking',
    directBanner: 'Precio directo garantizado · Sin comisiones · Confirmación inmediata',
    errorBooking: 'Error al crear la reserva. Inténtalo de nuevo.',
    waGreet: '¡Hola! Quiero reservar en Lapa Casa Rio.',
    waAwait: 'Quedo a la espera de confirmación. ¡Gracias!',
    cardGoToPayment: 'Ir al pago con tarjeta →',
    pmPixRec: 'Recomendado',
    pmPixOffer: 'Sin comisión · Precio directo',
    pmCardFee: '10% adicional con tarjeta',
    pmCardNote: 'Nacional o internacional',
    pmCardTotal: 'Total con tarjeta',
    pmNote: 'PIX: 30% sin recargo · Tarjeta de crédito: 10% extra',
    pmPixUnavailable: 'Disponible solo en Brasil',
    gpOr: 'O pagar en grupo',
    gpTitle: 'El hostel espera a tu grupo.',
    gpDesc:
      'Enviá el link ahora — cada miembro elige pagar con tarjeta o PIX desde su celular, completa sus datos y paga su cama.',
    gpMetaEach: 'cada persona paga aprox.',
    gpBtn: 'Generar link de pago grupal',
    gpLoading: 'Generando link...',
    gpCopy: 'Copiar link',
    gpCopied: 'Copiado',
    gpShareWa: 'Compartir por WhatsApp',
    gpExpire: 'El link expira en 10 minutos. Todos los integrantes deben pagar en ese plazo.',
    gpErrGeneric: 'Error al generar el link. Intentá de nuevo.',
  },
  en: {
    step1: 'Dates',
    step2: 'Rooms',
    step3: 'Guest',
    step4: 'Summary',
    p1title: 'Choose your dates',
    p1sub: 'Select check-in and check-out',
    checkin: 'Check-in',
    checkout: 'Check-out',
    calPrev: 'Previous month',
    calNext: 'Next month',
    seasonMedia: '⛅ Mid season: ×1.0',
    seasonAlta: '☀️ High (Dec–Mar, Jul–Aug): ×1.5',
    seasonCarnaval: '🎉 Carnival (min. 5 nights): ×2.0',
    seasonBaixa: '🌧 Low (Jun, Sep): ×0.8',
    p2title: 'Select your rooms',
    p2sub: 'How many beds do you need?',
    p3title: 'Guest details',
    p3sub: 'Booking contact',
    lblName: 'Full name',
    errName: 'Full name is required',
    lblEmail: 'Email',
    errEmail: 'Invalid email',
    lblEmail2: 'Confirm email',
    errEmail2: 'Emails do not match',
    noPaste: '(no paste)',
    lblPhone: 'WhatsApp',
    errPhone: 'Phone number required',
    lblCountry: 'Country',
    errCountry: 'Country required',
    selectPlaceholder: 'Select',
    optOther: 'Other',
    lblCPF: 'CPF',
    lblPassport: 'Passport / ID',
    errCPF: 'Invalid CPF',
    errDocForeign: 'Invalid document (min. 5 characters)',
    phCPF: '000.000.000-00',
    phPassport: 'Passport number',
    fbCPFok: 'Valid CPF',
    fbCPFerr: 'Invalid CPF',
    fbDocOk: 'Document accepted',
    restrictionText: "I confirm I've read and accept the house rules above.",
    errRestriction: 'You must confirm you have read and accept the restrictions.',
    lblDocPhoto: 'Document photo (ID / Passport)',
    docPhotoBtn: 'Tap to take a photo or upload an image',
    changeDocPhoto: 'Change photo',
    errDocPhoto: 'Document photo is required',
    lblArrival: 'Arrival time',
    errArrival: 'Arrival time required',
    arrivalPlaceholder: 'Select (2 pm–10 pm)',
    lblRequests: 'Special requests',
    optional: '(optional)',
    rulesTitle: 'House rules',
    rule1: 'Check-in: 2 pm–10 pm.',
    rule2: 'Check-out: by 12 pm.',
    rule3: 'ID required at check-in.',
    rule4: 'Guests must be 18 or older.',
    rule5: 'Smoking inside the hostel is not allowed.',
    rule6: 'Triple-decker bunk beds: not suitable for guests over 50 or with reduced mobility.',
    cancelBtn: 'Cancellation policy',
    cancelNo: 'Non-refundable',
    cancelNoText:
      'The deposit paid at booking is non-refundable in case of cancellation or no-show, regardless of notice.',
    p4title: 'Booking summary',
    p4sub: 'Review before confirming',
    sumDatesHead: 'Dates & Rooms',
    sumPriceHead: 'Price',
    sumGuestHead: 'Guest',
    pmPix: 'PIX',
    pmPixApproval: 'Instant approval',
    pmCard: 'Credit card',
    btnConfirm: 'Confirm booking',
    btnWhatsApp: 'Confirm via WhatsApp',
    successTitle: 'Booking confirmed!',
    successSub: 'We sent the details to your email and WhatsApp',
    pixDepLabel: 'PIX deposit',
    cardDepLabel: 'Card payment',
    cardInstruction: 'You will receive the payment link by email.',
    timerLabel: 'Expires in',
    pixKey: 'PIX key: lapalandiarj@gmail.com',
    restNote: 'The remaining 70% is due at check-in, in cash or by card.',
    referralTitle: 'Refer a friend, get a discount',
    referralBody:
      'Share this code: your friend gets 10% off and, once they book, you get another 10% code for your next stay.',
    referralCopy: 'Copy code',
    referralCopied: 'Copied!',
    btnNewBooking: 'New booking',
    btnBookOwnBed: 'Book my bed →',
    btnChangeMethod: 'Change payment method',
    payInitFailedMsg:
      'Your booking is confirmed, but we could not generate the payment code right now. Try again or contact us on WhatsApp.',
    paymentLinkErrorMsg:
      'We could not generate the payment link. Please try again or contact us on WhatsApp.',
    expiredTitle: 'Booking not completed',
    expiredSub: 'Time expired. The beds have been released.',
    btnTryAgain: 'Try again',
    priceBase: 'Base per night',
    btnBack: 'Back',
    btnNext: 'Next',
    flexibleNotice:
      'Room 6 — Women Only: female dorm by default. Converts to mixed 48h before check-in if needed.',
    tNights: 'Nights',
    tTotalBeds: 'Total beds',
    tTotal: 'Total',
    tDepositNow: 'Deposit now (PIX/Card)',
    tAtCheckin: 'at check-in',
    tNight: 'night',
    tNights2: 'nights',
    tBed: 'bed',
    tBeds: 'beds',
    tSelectCheckout: 'Select check-out',
    tClickCheckout: 'Click a check-out date',
    tInProgress: 'in progress',
    tCountryLabel: 'Country',
    tToastCheckin: 'Select a check-in date.',
    tToastCheckout: 'Select a check-out date.',
    tToastMinNights: 'minimum stay of',
    tToastNights: 'nights.',
    tToastBeds: 'Select at least 1 bed.',
    otaDirect: 'Booking direct saves you',
    otaVs: 'vs Airbnb/Booking',
    directBanner: 'Best rate guaranteed · No platform fees · Instant confirmation',
    errorBooking: 'Error creating booking. Please try again.',
    waGreet: 'Hello! I would like to book at Lapa Casa Rio.',
    waAwait: 'Looking forward to your confirmation. Thank you!',
    cardGoToPayment: 'Go to card payment →',
    pmPixRec: 'Recommended',
    pmPixOffer: 'No fees · Direct price',
    pmCardFee: '10% added for card',
    pmCardNote: 'Domestic or international',
    pmCardTotal: 'Total with card',
    pmNote: 'PIX: 30% no surcharge · Credit card: 10% extra',
    pmPixUnavailable: 'Available in Brazil only',
    gpOr: 'Or pay as a group',
    gpTitle: 'One link for the whole group',
    gpDesc:
      'Share this link however you like. Each person fills in their details and pays for their bed. When the last one pays, the booking is confirmed automatically.',
    gpMetaEach: 'each person pays approx.',
    gpBtn: 'Generate group payment link',
    gpLoading: 'Generating link...',
    gpCopy: 'Copy link',
    gpCopied: 'Copied',
    gpShareWa: 'Share via WhatsApp',
    gpExpire: 'The link expires in 10 minutes. All members must pay within this time.',
    gpErrGeneric: 'Error generating link. Please try again.',
  },
  fr: {
    step1: 'Dates',
    step2: 'Chambres',
    step3: 'Voyageur',
    step4: 'Récapitulatif',
    p1title: 'Choisissez vos dates',
    p1sub: 'Sélectionnez arrivée et départ',
    checkin: 'Arrivée',
    checkout: 'Départ',
    calPrev: 'Mois précédent',
    calNext: 'Mois suivant',
    seasonMedia: '⛅ Moyenne: ×1.0',
    seasonAlta: '☀️ Haute (Déc–Mar, Juil–Août): ×1.5',
    seasonCarnaval: '🎉 Carnaval (min. 5 nuits): ×2.0',
    seasonBaixa: '🌧 Basse (Juin, Sep): ×0.8',
    p2title: 'Sélectionnez les chambres',
    p2sub: 'De combien de lits avez-vous besoin?',
    p3title: 'Informations du voyageur',
    p3sub: 'Responsable de la réservation',
    lblName: 'Nom complet',
    errName: 'Le nom complet est obligatoire',
    lblEmail: 'E-mail',
    errEmail: 'E-mail invalide',
    lblEmail2: "Confirmer l'e-mail",
    errEmail2: 'Les e-mails ne correspondent pas',
    noPaste: '(ne pas coller)',
    lblPhone: 'WhatsApp',
    errPhone: 'Téléphone obligatoire',
    lblCountry: 'Pays',
    errCountry: 'Pays obligatoire',
    selectPlaceholder: 'Sélectionner',
    optOther: 'Autre',
    lblCPF: 'CPF',
    lblPassport: "Passeport / Pièce d'identité",
    errCPF: 'CPF invalide',
    errDocForeign: 'Document invalide (min. 5 caractères)',
    phCPF: '000.000.000-00',
    phPassport: 'Numéro de passeport',
    fbCPFok: 'CPF valide',
    fbCPFerr: 'CPF invalide',
    fbDocOk: 'Document accepté',
    restrictionText: 'Je confirme avoir lu et accepté les règles de la maison ci-dessus.',
    errRestriction: 'Vous devez confirmer avoir lu et accepté les restrictions.',
    lblDocPhoto: "Photo du document (pièce d'identité / passeport)",
    docPhotoBtn: 'Touchez pour prendre une photo ou envoyer une image',
    changeDocPhoto: 'Changer la photo',
    errDocPhoto: 'La photo du document est obligatoire',
    lblArrival: "Heure d'arrivée",
    errArrival: "Heure d'arrivée obligatoire",
    arrivalPlaceholder: 'Sélectionner (14h–22h)',
    lblRequests: 'Demandes spéciales',
    optional: '(facultatif)',
    rulesTitle: 'Règlement intérieur',
    rule1: 'Check-in: 14h–22h.',
    rule2: 'Check-out: avant 12h.',
    rule3: "Pièce d'identité obligatoire au check-in.",
    rule4: 'Hébergement réservé aux plus de 18 ans.',
    rule5: "Interdiction de fumer dans l'hostel.",
    rule6:
      'Lits superposés à trois niveaux : déconseillés aux personnes de plus de 50 ans ou à mobilité réduite.',
    cancelBtn: "Politique d'annulation",
    cancelNo: 'Non remboursable',
    cancelNoText:
      "L'acompte versé lors de la réservation n'est pas remboursable en cas d'annulation ou de non-présentation, quel que soit le délai de préavis.",
    p4title: 'Récapitulatif de la réservation',
    p4sub: 'Vérifiez avant de confirmer',
    sumDatesHead: 'Dates et Chambres',
    sumPriceHead: 'Prix',
    sumGuestHead: 'Voyageur',
    pmPix: 'PIX',
    pmPixApproval: 'Approbation immédiate',
    pmCard: 'Carte de crédit',
    btnConfirm: 'Confirmer la réservation',
    btnWhatsApp: 'Confirmer par WhatsApp',
    successTitle: 'Réservation confirmée!',
    successSub: 'Nous vous avons envoyé les détails par e-mail et WhatsApp',
    pixDepLabel: 'Acompte PIX',
    cardDepLabel: 'Paiement par carte',
    cardInstruction: 'Vous recevrez le lien de paiement par e-mail.',
    timerLabel: 'Expire dans',
    pixKey: 'Clé PIX: lapalandiarj@gmail.com',
    restNote: 'Les 70% restants sont payables au check-in, en espèces ou par carte.',
    referralTitle: 'Parrainez un ami, gagnez une réduction',
    referralBody:
      "Partagez ce code : votre ami a 10% de réduction et, dès qu'il réserve, vous recevez un autre code de 10% pour votre prochain séjour.",
    referralCopy: 'Copier le code',
    referralCopied: 'Copié !',
    btnNewBooking: 'Nouvelle réservation',
    btnBookOwnBed: 'Réserver mon lit →',
    btnChangeMethod: 'Changer de moyen de paiement',
    payInitFailedMsg:
      "Votre réservation est confirmée, mais nous n'avons pas pu générer le code de paiement pour le moment. Réessayez ou contactez-nous sur WhatsApp.",
    paymentLinkErrorMsg:
      "Nous n'avons pas pu générer le lien de paiement. Réessayez ou contactez-nous sur WhatsApp.",
    expiredTitle: 'Réservation non finalisée',
    expiredSub: 'Le délai est expiré. Les lits ont été libérés.',
    btnTryAgain: 'Réessayer',
    priceBase: 'Base par nuit',
    btnBack: 'Retour',
    btnNext: 'Suivant',
    flexibleNotice:
      'Chambre 6 — Femmes uniquement: dortoir féminin par défaut. Converti en mixte 48h avant le check-in si nécessaire.',
    tNights: 'Nuits',
    tTotalBeds: 'Total des lits',
    tTotal: 'Total',
    tDepositNow: 'Acompte (PIX/Carte)',
    tAtCheckin: 'au check-in',
    tNight: 'nuit',
    tNights2: 'nuits',
    tBed: 'lit',
    tBeds: 'lits',
    tSelectCheckout: 'Sélectionner le départ',
    tClickCheckout: 'Cliquez sur une date de départ',
    tInProgress: 'en cours',
    tCountryLabel: 'Pays',
    tToastCheckin: "Sélectionnez la date d'arrivée.",
    tToastCheckout: 'Sélectionnez la date de départ.',
    tToastMinNights: 'séjour minimum de',
    tToastNights: 'nuits.',
    tToastBeds: 'Sélectionnez au moins 1 lit.',
    otaDirect: 'Réserver en direct économise',
    otaVs: 'vs Airbnb/Booking',
    directBanner: 'Meilleur tarif garanti · Sans commission · Confirmation immédiate',
    errorBooking: 'Erreur lors de la réservation. Veuillez réessayer.',
    waGreet: 'Bonjour ! Je souhaite réserver au Lapa Casa Rio.',
    waAwait: "Dans l'attente de votre confirmation. Merci !",
    cardGoToPayment: 'Accéder au paiement par carte →',
    pmPixRec: 'Recommandé',
    pmPixOffer: 'Sans frais · Prix direct',
    pmCardFee: '10% supplément carte',
    pmCardNote: 'Nationale ou internationale',
    pmCardTotal: 'Total avec carte',
    pmNote: 'PIX: 30% sans frais · Carte de crédit: +10% en plus',
    pmPixUnavailable: 'Disponible au Brésil uniquement',
    gpOr: 'Ou payer en groupe',
    gpTitle: 'Un lien pour tout le groupe',
    gpDesc:
      'Partagez ce lien comme vous le souhaitez. Chaque personne remplit ses coordonnées et paie sa place. Quand le dernier paye, la réservation est confirmée automatiquement.',
    gpMetaEach: 'chaque personne paie environ',
    gpBtn: 'Générer le lien de paiement groupé',
    gpLoading: 'Génération en cours...',
    gpCopy: 'Copier le lien',
    gpCopied: 'Copié',
    gpShareWa: 'Partager via WhatsApp',
    gpExpire: 'Le lien expire dans 10 minutes. Tous les membres doivent payer dans ce délai.',
    gpErrGeneric: 'Erreur lors de la génération du lien. Réessayez.',
  },
  de: {
    step1: 'Daten',
    step2: 'Zimmer',
    step3: 'Gast',
    step4: 'Übersicht',
    p1title: 'Wählen Sie Ihre Daten',
    p1sub: 'An- und Abreisedatum auswählen',
    checkin: 'Anreise',
    checkout: 'Abreise',
    calPrev: 'Vorheriger Monat',
    calNext: 'Nächster Monat',
    seasonMedia: '⛅ Zwischensaison: ×1.0',
    seasonAlta: '☀️ Hochsaison (Dez–Mär, Jul–Aug): ×1.5',
    seasonCarnaval: '🎉 Karneval (mind. 5 Nächte): ×2.0',
    seasonBaixa: '🌧 Nebensaison (Jun, Sep): ×0.8',
    p2title: 'Zimmer auswählen',
    p2sub: 'Wie viele Betten benötigen Sie?',
    p3title: 'Gästedaten',
    p3sub: 'Verantwortlich für die Buchung',
    lblName: 'Vollständiger Name',
    errName: 'Vollständiger Name ist erforderlich',
    lblEmail: 'E-Mail',
    errEmail: 'Ungültige E-Mail',
    lblEmail2: 'E-Mail bestätigen',
    errEmail2: 'E-Mail-Adressen stimmen nicht überein',
    noPaste: '(nicht einfügen)',
    lblPhone: 'WhatsApp',
    errPhone: 'Telefonnummer erforderlich',
    lblCountry: 'Land',
    errCountry: 'Land erforderlich',
    selectPlaceholder: 'Auswählen',
    optOther: 'Andere',
    lblCPF: 'CPF',
    lblPassport: 'Reisepass / Ausweis',
    errCPF: 'Ungültige CPF',
    errDocForeign: 'Ungültiges Dokument (mind. 5 Zeichen)',
    phCPF: '000.000.000-00',
    phPassport: 'Reisepassnummer',
    fbCPFok: 'CPF gültig',
    fbCPFerr: 'CPF ungültig',
    fbDocOk: 'Dokument akzeptiert',
    restrictionText: 'Ich bestätige, die obigen Hausregeln gelesen und akzeptiert zu haben.',
    errRestriction: 'Du musst bestätigen, dass du die Einschränkungen gelesen und akzeptiert hast.',
    lblDocPhoto: 'Ausweisfoto (Ausweis / Reisepass)',
    docPhotoBtn: 'Tippen, um ein Foto aufzunehmen oder hochzuladen',
    changeDocPhoto: 'Foto ändern',
    errDocPhoto: 'Ausweisfoto ist erforderlich',
    lblArrival: 'Ankunftszeit',
    errArrival: 'Ankunftszeit erforderlich',
    arrivalPlaceholder: 'Auswählen (14–22 Uhr)',
    lblRequests: 'Sonderwünsche',
    optional: '(optional)',
    rulesTitle: 'Hausregeln',
    rule1: 'Check-in: 14–22 Uhr.',
    rule2: 'Check-out: bis 12 Uhr.',
    rule3: 'Personalausweis beim Check-in erforderlich.',
    rule4: 'Unterkunft nur für Personen ab 18 Jahren.',
    rule5: 'Rauchen im Hostel ist verboten.',
    rule6:
      'Dreistöckige Etagenbetten: nicht geeignet für Gäste über 50 oder mit eingeschränkter Mobilität.',
    cancelBtn: 'Stornierungsbedingungen',
    cancelNo: 'Nicht erstattungsfähig',
    cancelNoText:
      'Die bei der Buchung gezahlte Anzahlung ist bei Stornierung oder Nichterscheinen nicht erstattungsfähig, unabhängig von der Vorlaufzeit.',
    p4title: 'Buchungsübersicht',
    p4sub: 'Vor der Bestätigung prüfen',
    sumDatesHead: 'Daten & Zimmer',
    sumPriceHead: 'Preis',
    sumGuestHead: 'Gast',
    pmPix: 'PIX',
    pmPixApproval: 'Sofortige Genehmigung',
    pmCard: 'Kreditkarte',
    btnConfirm: 'Buchung bestätigen',
    btnWhatsApp: 'Per WhatsApp bestätigen',
    successTitle: 'Buchung bestätigt!',
    successSub: 'Wir haben die Details per E-Mail und WhatsApp gesendet',
    pixDepLabel: 'PIX-Anzahlung',
    cardDepLabel: 'Kartenzahlung',
    cardInstruction: 'Sie erhalten den Zahlungslink per E-Mail.',
    timerLabel: 'Läuft ab in',
    pixKey: 'PIX-Schlüssel: lapalandiarj@gmail.com',
    restNote: 'Die verbleibenden 70% werden beim Check-in bar oder per Karte bezahlt.',
    referralTitle: 'Freund empfehlen, Rabatt bekommen',
    referralBody:
      'Teilen Sie diesen Code: Ihr Freund erhält 10% Rabatt, und sobald er bucht, bekommen Sie einen weiteren 10%-Code für Ihren nächsten Aufenthalt.',
    referralCopy: 'Code kopieren',
    referralCopied: 'Kopiert!',
    btnNewBooking: 'Neue Buchung',
    btnBookOwnBed: 'Mein Bett buchen →',
    btnChangeMethod: 'Zahlungsmethode ändern',
    payInitFailedMsg:
      'Ihre Buchung ist bestätigt, aber wir konnten den Zahlungscode gerade nicht erstellen. Versuchen Sie es erneut oder kontaktieren Sie uns per WhatsApp.',
    paymentLinkErrorMsg:
      'Wir konnten den Zahlungslink nicht erstellen. Versuchen Sie es erneut oder kontaktieren Sie uns per WhatsApp.',
    expiredTitle: 'Buchung nicht abgeschlossen',
    expiredSub: 'Zeit abgelaufen. Die Betten wurden freigegeben.',
    btnTryAgain: 'Erneut versuchen',
    priceBase: 'Grundpreis pro Nacht',
    btnBack: 'Zurück',
    btnNext: 'Weiter',
    flexibleNotice:
      'Zimmer 6 — Nur Frauen: standardmäßig Frauenschlafraum. Wird 48h vor dem Check-in bei Bedarf gemischt.',
    tNights: 'Nächte',
    tTotalBeds: 'Betten gesamt',
    tTotal: 'Gesamt',
    tDepositNow: 'Anzahlung (PIX/Karte)',
    tAtCheckin: 'beim Check-in',
    tNight: 'Nacht',
    tNights2: 'Nächte',
    tBed: 'Bett',
    tBeds: 'Betten',
    tSelectCheckout: 'Abreise auswählen',
    tClickCheckout: 'Klicken Sie auf ein Abreisedatum',
    tInProgress: 'läuft',
    tCountryLabel: 'Land',
    tToastCheckin: 'Bitte wählen Sie ein Anreisedatum.',
    tToastCheckout: 'Bitte wählen Sie ein Abreisedatum.',
    tToastMinNights: 'Mindestaufenthalt von',
    tToastNights: 'Nächten.',
    tToastBeds: 'Bitte wählen Sie mindestens 1 Bett.',
    otaDirect: 'Direktbuchung spart',
    otaVs: 'vs Airbnb/Booking',
    directBanner: 'Bestpreis garantiert · Keine Provisionen · Sofortbestätigung',
    errorBooking: 'Fehler bei der Buchungserstellung. Bitte erneut versuchen.',
    waGreet: 'Hallo! Ich möchte im Lapa Casa Rio buchen.',
    waAwait: 'Ich freue mich auf Ihre Bestätigung. Vielen Dank!',
    cardGoToPayment: 'Zur Kartenzahlung →',
    pmPixRec: 'Empfohlen',
    pmPixOffer: 'Keine Gebühren · Direktpreis',
    pmCardFee: '10% Aufpreis Karte',
    pmCardNote: 'Inland oder Ausland',
    pmCardTotal: 'Gesamt mit Karte',
    pmNote: 'PIX: 30% ohne Aufpreis · Kreditkarte: +10% extra',
    pmPixUnavailable: 'Nur in Brasilien verfügbar',
    gpOr: 'Oder als Gruppe zahlen',
    gpTitle: 'Ein Link für die ganze Gruppe',
    gpDesc:
      'Teile diesen Link, wie du möchtest. Jede Person trägt ihre Daten ein und bezahlt ihr Bett. Wenn der Letzte bezahlt hat, wird die Buchung automatisch bestätigt.',
    gpMetaEach: 'jede Person zahlt ca.',
    gpBtn: 'Gruppenlink erstellen',
    gpLoading: 'Link wird erstellt...',
    gpCopy: 'Link kopieren',
    gpCopied: 'Kopiert',
    gpShareWa: 'Per WhatsApp teilen',
    gpExpire:
      'Der Link läuft in 10 Minuten ab. Alle Mitglieder müssen innerhalb dieser Zeit zahlen.',
    gpErrGeneric: 'Fehler beim Erstellen des Links. Erneut versuchen.',
  },
  it: {
    step1: 'Date',
    step2: 'Camere',
    step3: 'Ospite',
    step4: 'Riepilogo',
    p1title: 'Scegli le tue date',
    p1sub: 'Seleziona arrivo e partenza',
    checkin: 'Check-in',
    checkout: 'Check-out',
    calPrev: 'Mese precedente',
    calNext: 'Mese successivo',
    seasonMedia: '⛅ Media: ×1.0',
    seasonAlta: '☀️ Alta (Dic–Mar, Lug–Ago): ×1.5',
    seasonCarnaval: '🎉 Carnevale (min. 5 notti): ×2.0',
    seasonBaixa: '🌧 Bassa (Giu, Set): ×0.8',
    p2title: 'Seleziona le camere',
    p2sub: 'Quanti letti ti servono?',
    p3title: "Dati dell'ospite",
    p3sub: 'Responsabile della prenotazione',
    lblName: 'Nome completo',
    errName: 'Il nome completo è obbligatorio',
    lblEmail: 'E-mail',
    errEmail: 'E-mail non valida',
    lblEmail2: 'Conferma e-mail',
    errEmail2: 'Le e-mail non corrispondono',
    noPaste: '(non incollare)',
    lblPhone: 'WhatsApp',
    errPhone: 'Telefono obbligatorio',
    lblCountry: 'Paese',
    errCountry: 'Paese obbligatorio',
    selectPlaceholder: 'Seleziona',
    optOther: 'Altro',
    lblCPF: 'CPF',
    lblPassport: 'Passaporto / Documento',
    errCPF: 'CPF non valido',
    errDocForeign: 'Documento non valido (min. 5 caratteri)',
    phCPF: '000.000.000-00',
    phPassport: 'Numero di passaporto',
    fbCPFok: 'CPF valido',
    fbCPFerr: 'CPF non valido',
    fbDocOk: 'Documento accettato',
    restrictionText: 'Confermo di aver letto e accettato le regole della casa sopra.',
    errRestriction: 'Devi confermare di aver letto e accettato le restrizioni.',
    lblDocPhoto: "Foto del documento (carta d'identità / passaporto)",
    docPhotoBtn: "Tocca per scattare una foto o caricare un'immagine",
    changeDocPhoto: 'Cambia foto',
    errDocPhoto: 'La foto del documento è obbligatoria',
    lblArrival: 'Orario di arrivo',
    errArrival: 'Orario di arrivo obbligatorio',
    arrivalPlaceholder: 'Seleziona (14h–22h)',
    lblRequests: 'Richieste speciali',
    optional: '(facoltativo)',
    rulesTitle: 'Regole della casa',
    rule1: 'Check-in: 14h–22h.',
    rule2: 'Check-out: entro le 12h.',
    rule3: "Documento d'identità obbligatorio al check-in.",
    rule4: 'Soggiorno consentito a partire dai 18 anni.',
    rule5: "Vietato fumare all'interno dell'hostel.",
    rule6: 'Letti a castello a tre livelli: non adatti a ospiti over 50 o con mobilità ridotta.',
    cancelBtn: 'Politica di cancellazione',
    cancelNo: 'Non rimborsabile',
    cancelNoText:
      'La caparra pagata al momento della prenotazione non è rimborsabile in caso di cancellazione o no-show, indipendentemente dal preavviso.',
    p4title: 'Riepilogo prenotazione',
    p4sub: 'Controlla prima di confermare',
    sumDatesHead: 'Date e Camere',
    sumPriceHead: 'Prezzo',
    sumGuestHead: 'Ospite',
    pmPix: 'PIX',
    pmPixApproval: 'Approvazione immediata',
    pmCard: 'Carta di credito',
    btnConfirm: 'Conferma prenotazione',
    btnWhatsApp: 'Conferma via WhatsApp',
    successTitle: 'Prenotazione confermata!',
    successSub: 'Abbiamo inviato i dettagli via e-mail e WhatsApp',
    pixDepLabel: 'Acconto PIX',
    cardDepLabel: 'Pagamento con carta',
    cardInstruction: 'Riceverai il link di pagamento via e-mail.',
    timerLabel: 'Scade tra',
    pixKey: 'Chiave PIX: lapalandiarj@gmail.com',
    restNote: 'Il restante 70% è dovuto al check-in, in contanti o con carta.',
    referralTitle: 'Consiglia un amico, ottieni uno sconto',
    referralBody:
      'Condividi questo codice: il tuo amico ha il 10% di sconto e, quando prenota, tu ricevi un altro codice del 10% per il tuo prossimo soggiorno.',
    referralCopy: 'Copia codice',
    referralCopied: 'Copiato!',
    btnNewBooking: 'Nuova prenotazione',
    btnBookOwnBed: 'Prenota il mio letto →',
    btnChangeMethod: 'Cambia metodo di pagamento',
    payInitFailedMsg:
      'La tua prenotazione è confermata, ma al momento non siamo riusciti a generare il codice di pagamento. Riprova o scrivici su WhatsApp.',
    paymentLinkErrorMsg:
      'Non siamo riusciti a generare il link di pagamento. Riprova o scrivici su WhatsApp.',
    expiredTitle: 'Prenotazione non completata',
    expiredSub: 'Il tempo è scaduto. I posti sono stati liberati.',
    btnTryAgain: 'Riprova',
    priceBase: 'Base per notte',
    btnBack: 'Indietro',
    btnNext: 'Avanti',
    flexibleNotice:
      'Camera 6 — Solo Donne: dormitorio femminile per impostazione predefinita. Diventa misto 48h prima del check-in se necessario.',
    tNights: 'Notti',
    tTotalBeds: 'Letti totali',
    tTotal: 'Totale',
    tDepositNow: 'Acconto (PIX/Carta)',
    tAtCheckin: 'al check-in',
    tNight: 'notte',
    tNights2: 'notti',
    tBed: 'letto',
    tBeds: 'letti',
    tSelectCheckout: 'Seleziona check-out',
    tClickCheckout: 'Clicca su una data di partenza',
    tInProgress: 'in corso',
    tCountryLabel: 'Paese',
    tToastCheckin: 'Seleziona la data di check-in.',
    tToastCheckout: 'Seleziona la data di check-out.',
    tToastMinNights: 'soggiorno minimo di',
    tToastNights: 'notti.',
    tToastBeds: 'Seleziona almeno 1 letto.',
    otaDirect: 'Prenotare direttamente risparmia',
    otaVs: 'vs Airbnb/Booking',
    directBanner: 'Miglior tariffa garantita · Nessuna commissione · Conferma immediata',
    errorBooking: 'Errore durante la creazione della prenotazione. Riprova.',
    waGreet: 'Ciao! Vorrei prenotare al Lapa Casa Rio.',
    waAwait: 'In attesa della vostra conferma. Grazie!',
    cardGoToPayment: 'Vai al pagamento con carta →',
    pmPixRec: 'Consigliato',
    pmPixOffer: 'Senza commissioni · Prezzo diretto',
    pmCardFee: '10% in più con carta',
    pmCardNote: 'Nazionale o internazionale',
    pmCardTotal: 'Totale con carta',
    pmNote: 'PIX: 30% senza costi aggiuntivi · Carta di credito: +10% in più',
    pmPixUnavailable: 'Disponibile solo in Brasile',
    gpOr: 'Oppure pagare in gruppo',
    gpTitle: 'Un link per tutto il gruppo',
    gpDesc:
      "Condividi questo link dove vuoi. Ogni persona inserisce i propri dati e paga il proprio posto. Quando l'ultimo paga, la prenotazione viene confermata automaticamente.",
    gpMetaEach: 'ogni persona paga circa',
    gpBtn: 'Genera link di pagamento di gruppo',
    gpLoading: 'Generazione in corso...',
    gpCopy: 'Copia link',
    gpCopied: 'Copiato',
    gpShareWa: 'Condividi via WhatsApp',
    gpExpire: 'Il link scade in 10 minuti. Tutti i membri devono pagare entro questo termine.',
    gpErrGeneric: 'Errore durante la generazione del link. Riprova.',
  },
} as const;

export type Translations = (typeof T)[Lang];

// ─── Cuartos por defecto (fallback si la API no responde) ─
export const DEFAULT_ROOMS: RoomDef[] = [
  {
    id: 'cuarto1',
    code: 'mixto_12a',
    name: 'Cuarto 1',
    type: 'mixed',
    capacity: 12,
    available: 12,
    price: 85,
    isFlexible: false,
  },
  {
    id: 'cuarto3',
    code: 'mixto_12b',
    name: 'Cuarto 3',
    type: 'mixed',
    capacity: 12,
    available: 12,
    price: 85,
    isFlexible: false,
  },
  {
    id: 'cuarto4',
    code: 'mixto_7',
    name: 'Cuarto 4',
    type: 'mixed',
    capacity: 7,
    available: 7,
    price: 85,
    isFlexible: false,
  },
  {
    id: 'cuarto5',
    code: 'mixto_7c',
    name: 'Cuarto 5',
    type: 'mixed',
    capacity: 7,
    available: 7,
    price: 85,
    isFlexible: false,
  },
  {
    id: 'cuarto6',
    code: 'flexible_7',
    name: 'Cuarto 6',
    type: 'female',
    capacity: 7,
    available: 7,
    price: 85,
    isFlexible: true,
  },
];

// ─── Labels de calendario ─────────────────────────────────
export const DAY_LBL: Record<Lang, string[]> = {
  pt: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  es: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  fr: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
  de: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  it: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
};

export const MON_LBL: Record<Lang, string[]> = {
  pt: [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro',
  ],
  es: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
  en: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  fr: [
    'Janvier',
    'Février',
    'Mars',
    'Avril',
    'Mai',
    'Juin',
    'Juillet',
    'Août',
    'Septembre',
    'Octobre',
    'Novembre',
    'Décembre',
  ],
  de: [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember',
  ],
  it: [
    'Gennaio',
    'Febbraio',
    'Marzo',
    'Aprile',
    'Maggio',
    'Giugno',
    'Luglio',
    'Agosto',
    'Settembre',
    'Ottobre',
    'Novembre',
    'Dicembre',
  ],
};
