name: Fly.io logs (debug, read-only)

on:
  workflow_dispatch:

jobs:
  logs:
    name: Fetch recent logs
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl ssh console -a lapa-casa-hostel -C "node database/scripts/migrate.js"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
